/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import UserDataDTO from './gp.backend.model/UserDataDTO';
import UserResponseDTO from './gp.backend.model/UserResponseDTO';
import UserControllerApi from './gp.backend.api/UserControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BackendClient = require('index'); // See note below*.
* var xxxSvc = new BackendClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BackendClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BackendClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BackendClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The UserDataDTO model constructor.
     * @property {module:gp.backend.model/UserDataDTO}
     */
    UserDataDTO,

    /**
     * The UserResponseDTO model constructor.
     * @property {module:gp.backend.model/UserResponseDTO}
     */
    UserResponseDTO,

    /**
    * The UserControllerApi service constructor.
    * @property {module:gp.backend.api/UserControllerApi}
    */
    UserControllerApi
};
