/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BookedTurnQueue from './model/BookedTurnQueue';
import Branch from './model/Branch';
import Employee from './model/Employee';
import Institute from './model/Institute';
import Queue from './model/Queue';
import QueueSpec from './model/QueueSpec';
import BranchesControllerApi from './api/BranchesControllerApi';
import EmployeesControllerApi from './api/EmployeesControllerApi';
import InstituteControllerApi from './api/InstituteControllerApi';
import QueueControllerApi from './api/QueueControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BookedTurnQueue model constructor.
     * @property {module:model/BookedTurnQueue}
     */
    BookedTurnQueue,

    /**
     * The Branch model constructor.
     * @property {module:model/Branch}
     */
    Branch,

    /**
     * The Employee model constructor.
     * @property {module:model/Employee}
     */
    Employee,

    /**
     * The Institute model constructor.
     * @property {module:model/Institute}
     */
    Institute,

    /**
     * The Queue model constructor.
     * @property {module:model/Queue}
     */
    Queue,

    /**
     * The QueueSpec model constructor.
     * @property {module:model/QueueSpec}
     */
    QueueSpec,

    /**
    * The BranchesControllerApi service constructor.
    * @property {module:api/BranchesControllerApi}
    */
    BranchesControllerApi,

    /**
    * The EmployeesControllerApi service constructor.
    * @property {module:api/EmployeesControllerApi}
    */
    EmployeesControllerApi,

    /**
    * The InstituteControllerApi service constructor.
    * @property {module:api/InstituteControllerApi}
    */
    InstituteControllerApi,

    /**
    * The QueueControllerApi service constructor.
    * @property {module:api/QueueControllerApi}
    */
    QueueControllerApi
};
