/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackendClient);
  }
}(this, function(expect, BackendClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackendClient.InstituteControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InstituteControllerApi', function() {
    describe('createInstitute', function() {
      it('should call createInstitute successfully', function(done) {
        //uncomment below and update the code to test createInstitute
        //instance.createInstitute(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteInstitute', function() {
      it('should call deleteInstitute successfully', function(done) {
        //uncomment below and update the code to test deleteInstitute
        //instance.deleteInstitute(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getInstitute', function() {
      it('should call getInstitute successfully', function(done) {
        //uncomment below and update the code to test getInstitute
        //instance.getInstitute(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('loginAsInstitute', function() {
      it('should call loginAsInstitute successfully', function(done) {
        //uncomment below and update the code to test loginAsInstitute
        //instance.loginAsInstitute(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchInstitutes', function() {
      it('should call searchInstitutes successfully', function(done) {
        //uncomment below and update the code to test searchInstitutes
        //instance.searchInstitutes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateInstitute', function() {
      it('should call updateInstitute successfully', function(done) {
        //uncomment below and update the code to test updateInstitute
        //instance.updateInstitute(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
