/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackendClient);
  }
}(this, function(expect, BackendClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackendClient.BookedTurnQueue();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BookedTurnQueue', function() {
    it('should create an instance of BookedTurnQueue', function() {
      // uncomment below and update the code to test BookedTurnQueue
      //var instance = new BackendClient.BookedTurnQueue();
      //expect(instance).to.be.a(BackendClient.BookedTurnQueue);
    });

    it('should have the property turnId (base name: "turnId")', function() {
      // uncomment below and update the code to test the property turnId
      //var instance = new BackendClient.BookedTurnQueue();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new BackendClient.BookedTurnQueue();
      //expect(instance).to.be();
    });

    it('should have the property logoUrl (base name: "logoUrl")', function() {
      // uncomment below and update the code to test the property logoUrl
      //var instance = new BackendClient.BookedTurnQueue();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new BackendClient.BookedTurnQueue();
      //expect(instance).to.be();
    });

    it('should have the property queue (base name: "queue")', function() {
      // uncomment below and update the code to test the property queue
      //var instance = new BackendClient.BookedTurnQueue();
      //expect(instance).to.be();
    });

  });

}));
