/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackendClient);
  }
}(this, function(expect, BackendClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackendClient.SecurityConfiguration();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SecurityConfiguration', function() {
    it('should create an instance of SecurityConfiguration', function() {
      // uncomment below and update the code to test SecurityConfiguration
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be.a(BackendClient.SecurityConfiguration);
    });

    it('should have the property apiKey (base name: "apiKey")', function() {
      // uncomment below and update the code to test the property apiKey
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property apiKeyVehicle (base name: "apiKeyVehicle")', function() {
      // uncomment below and update the code to test the property apiKeyVehicle
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property apiKeyName (base name: "apiKeyName")', function() {
      // uncomment below and update the code to test the property apiKeyName
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "clientId")', function() {
      // uncomment below and update the code to test the property clientId
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property clientSecret (base name: "clientSecret")', function() {
      // uncomment below and update the code to test the property clientSecret
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property realm (base name: "realm")', function() {
      // uncomment below and update the code to test the property realm
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property appName (base name: "appName")', function() {
      // uncomment below and update the code to test the property appName
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property scopeSeparator (base name: "scopeSeparator")', function() {
      // uncomment below and update the code to test the property scopeSeparator
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property additionalQueryStringParams (base name: "additionalQueryStringParams")', function() {
      // uncomment below and update the code to test the property additionalQueryStringParams
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property useBasicAuthenticationWithAccessCodeGrant (base name: "useBasicAuthenticationWithAccessCodeGrant")', function() {
      // uncomment below and update the code to test the property useBasicAuthenticationWithAccessCodeGrant
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property enableCsrfSupport (base name: "enableCsrfSupport")', function() {
      // uncomment below and update the code to test the property enableCsrfSupport
      //var instance = new BackendClient.SecurityConfiguration();
      //expect(instance).to.be();
    });

  });

}));
