/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackendClient);
  }
}(this, function(expect, BackendClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackendClient.UiConfiguration();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UiConfiguration', function() {
    it('should create an instance of UiConfiguration', function() {
      // uncomment below and update the code to test UiConfiguration
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be.a(BackendClient.UiConfiguration);
    });

    it('should have the property deepLinking (base name: "deepLinking")', function() {
      // uncomment below and update the code to test the property deepLinking
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property displayOperationId (base name: "displayOperationId")', function() {
      // uncomment below and update the code to test the property displayOperationId
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property defaultModelsExpandDepth (base name: "defaultModelsExpandDepth")', function() {
      // uncomment below and update the code to test the property defaultModelsExpandDepth
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property defaultModelExpandDepth (base name: "defaultModelExpandDepth")', function() {
      // uncomment below and update the code to test the property defaultModelExpandDepth
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property defaultModelRendering (base name: "defaultModelRendering")', function() {
      // uncomment below and update the code to test the property defaultModelRendering
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property displayRequestDuration (base name: "displayRequestDuration")', function() {
      // uncomment below and update the code to test the property displayRequestDuration
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property docExpansion (base name: "docExpansion")', function() {
      // uncomment below and update the code to test the property docExpansion
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property filter (base name: "filter")', function() {
      // uncomment below and update the code to test the property filter
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property maxDisplayedTags (base name: "maxDisplayedTags")', function() {
      // uncomment below and update the code to test the property maxDisplayedTags
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property operationsSorter (base name: "operationsSorter")', function() {
      // uncomment below and update the code to test the property operationsSorter
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property showExtensions (base name: "showExtensions")', function() {
      // uncomment below and update the code to test the property showExtensions
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property showCommonExtensions (base name: "showCommonExtensions")', function() {
      // uncomment below and update the code to test the property showCommonExtensions
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property tagsSorter (base name: "tagsSorter")', function() {
      // uncomment below and update the code to test the property tagsSorter
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property validatorUrl (base name: "validatorUrl")', function() {
      // uncomment below and update the code to test the property validatorUrl
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property supportedSubmitMethods (base name: "supportedSubmitMethods")', function() {
      // uncomment below and update the code to test the property supportedSubmitMethods
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property swaggerBaseUiUrl (base name: "swaggerBaseUiUrl")', function() {
      // uncomment below and update the code to test the property swaggerBaseUiUrl
      //var instance = new BackendClient.UiConfiguration();
      //expect(instance).to.be();
    });

  });

}));
