/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserDataDTO model module.
 * @module gp.backend.model/UserDataDTO
 * @version v1
 */
class UserDataDTO {
    /**
     * Constructs a new <code>UserDataDTO</code>.
     * @alias module:gp.backend.model/UserDataDTO
     */
    constructor() { 
        
        UserDataDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserDataDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:gp.backend.model/UserDataDTO} obj Optional instance to populate.
     * @return {module:gp.backend.model/UserDataDTO} The populated <code>UserDataDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDataDTO();

            if (data.hasOwnProperty('appUserRoles')) {
                obj['appUserRoles'] = ApiClient.convertToType(data['appUserRoles'], ['String']);
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('instituteId')) {
                obj['instituteId'] = ApiClient.convertToType(data['instituteId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:gp.backend.model/UserDataDTO.AppUserRolesEnum>} appUserRoles
 */
UserDataDTO.prototype['appUserRoles'] = undefined;

/**
 * @member {String} username
 */
UserDataDTO.prototype['username'] = undefined;

/**
 * @member {String} password
 */
UserDataDTO.prototype['password'] = undefined;

/**
 * @member {String} instituteId
 */
UserDataDTO.prototype['instituteId'] = undefined;





/**
 * Allowed values for the <code>appUserRoles</code> property.
 * @enum {String}
 * @readonly
 */
UserDataDTO['AppUserRolesEnum'] = {

    /**
     * value: "ROLE_ADMIN"
     * @const
     */
    "ADMIN": "ROLE_ADMIN",

    /**
     * value: "ROLE_MANAGEMENT"
     * @const
     */
    "MANAGEMENT": "ROLE_MANAGEMENT",

    /**
     * value: "ROLE_HELP_DESK"
     * @const
     */
    "HELP_DESK": "ROLE_HELP_DESK"
};



export default UserDataDTO;

