/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserResponseDTO model module.
 * @module gp.backend.model/UserResponseDTO
 * @version v1
 */
class UserResponseDTO {
    /**
     * Constructs a new <code>UserResponseDTO</code>.
     * @alias module:gp.backend.model/UserResponseDTO
     */
    constructor() { 
        
        UserResponseDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserResponseDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:gp.backend.model/UserResponseDTO} obj Optional instance to populate.
     * @return {module:gp.backend.model/UserResponseDTO} The populated <code>UserResponseDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserResponseDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('appUserRoles')) {
                obj['appUserRoles'] = ApiClient.convertToType(data['appUserRoles'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
UserResponseDTO.prototype['id'] = undefined;

/**
 * @member {String} username
 */
UserResponseDTO.prototype['username'] = undefined;

/**
 * @member {String} email
 */
UserResponseDTO.prototype['email'] = undefined;

/**
 * @member {Array.<module:gp.backend.model/UserResponseDTO.AppUserRolesEnum>} appUserRoles
 */
UserResponseDTO.prototype['appUserRoles'] = undefined;





/**
 * Allowed values for the <code>appUserRoles</code> property.
 * @enum {String}
 * @readonly
 */
UserResponseDTO['AppUserRolesEnum'] = {

    /**
     * value: "ROLE_ADMIN"
     * @const
     */
    "ADMIN": "ROLE_ADMIN",

    /**
     * value: "ROLE_MANAGEMENT"
     * @const
     */
    "MANAGEMENT": "ROLE_MANAGEMENT",

    /**
     * value: "ROLE_HELP_DESK"
     * @const
     */
    "HELP_DESK": "ROLE_HELP_DESK"
};



export default UserResponseDTO;

