/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Queue from './Queue';

/**
 * The BookedTurnQueue model module.
 * @module gp.backend.model/BookedTurnQueue
 * @version v1
 */
class BookedTurnQueue {
    /**
     * Constructs a new <code>BookedTurnQueue</code>.
     * @alias module:gp.backend.model/BookedTurnQueue
     */
    constructor() { 
        
        BookedTurnQueue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookedTurnQueue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:gp.backend.model/BookedTurnQueue} obj Optional instance to populate.
     * @return {module:gp.backend.model/BookedTurnQueue} The populated <code>BookedTurnQueue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookedTurnQueue();

            if (data.hasOwnProperty('turnId')) {
                obj['turnId'] = ApiClient.convertToType(data['turnId'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('logoUrl')) {
                obj['logoUrl'] = ApiClient.convertToType(data['logoUrl'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('queue')) {
                obj['queue'] = Queue.constructFromObject(data['queue']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} turnId
 */
BookedTurnQueue.prototype['turnId'] = undefined;

/**
 * @member {Number} position
 */
BookedTurnQueue.prototype['position'] = undefined;

/**
 * @member {String} logoUrl
 */
BookedTurnQueue.prototype['logoUrl'] = undefined;

/**
 * @member {module:gp.backend.model/BookedTurnQueue.StateEnum} state
 */
BookedTurnQueue.prototype['state'] = undefined;

/**
 * @member {module:gp.backend.model/Queue} queue
 */
BookedTurnQueue.prototype['queue'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
BookedTurnQueue['StateEnum'] = {

    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",

    /**
     * value: "CANCELLED"
     * @const
     */
    "CANCELLED": "CANCELLED",

    /**
     * value: "COMPLETED"
     * @const
     */
    "COMPLETED": "COMPLETED"
};



export default BookedTurnQueue;

