/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SecurityConfiguration model module.
 * @module gp.backend.model/SecurityConfiguration
 * @version v0
 */
class SecurityConfiguration {
    /**
     * Constructs a new <code>SecurityConfiguration</code>.
     * @alias module:gp.backend.model/SecurityConfiguration
     */
    constructor() { 
        
        SecurityConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecurityConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:gp.backend.model/SecurityConfiguration} obj Optional instance to populate.
     * @return {module:gp.backend.model/SecurityConfiguration} The populated <code>SecurityConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecurityConfiguration();

            if (data.hasOwnProperty('apiKey')) {
                obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
            }
            if (data.hasOwnProperty('apiKeyVehicle')) {
                obj['apiKeyVehicle'] = ApiClient.convertToType(data['apiKeyVehicle'], 'String');
            }
            if (data.hasOwnProperty('apiKeyName')) {
                obj['apiKeyName'] = ApiClient.convertToType(data['apiKeyName'], 'String');
            }
            if (data.hasOwnProperty('clientId')) {
                obj['clientId'] = ApiClient.convertToType(data['clientId'], 'String');
            }
            if (data.hasOwnProperty('clientSecret')) {
                obj['clientSecret'] = ApiClient.convertToType(data['clientSecret'], 'String');
            }
            if (data.hasOwnProperty('realm')) {
                obj['realm'] = ApiClient.convertToType(data['realm'], 'String');
            }
            if (data.hasOwnProperty('appName')) {
                obj['appName'] = ApiClient.convertToType(data['appName'], 'String');
            }
            if (data.hasOwnProperty('scopeSeparator')) {
                obj['scopeSeparator'] = ApiClient.convertToType(data['scopeSeparator'], 'String');
            }
            if (data.hasOwnProperty('additionalQueryStringParams')) {
                obj['additionalQueryStringParams'] = ApiClient.convertToType(data['additionalQueryStringParams'], {'String': Object});
            }
            if (data.hasOwnProperty('useBasicAuthenticationWithAccessCodeGrant')) {
                obj['useBasicAuthenticationWithAccessCodeGrant'] = ApiClient.convertToType(data['useBasicAuthenticationWithAccessCodeGrant'], 'Boolean');
            }
            if (data.hasOwnProperty('enableCsrfSupport')) {
                obj['enableCsrfSupport'] = ApiClient.convertToType(data['enableCsrfSupport'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} apiKey
 */
SecurityConfiguration.prototype['apiKey'] = undefined;

/**
 * @member {String} apiKeyVehicle
 */
SecurityConfiguration.prototype['apiKeyVehicle'] = undefined;

/**
 * @member {String} apiKeyName
 */
SecurityConfiguration.prototype['apiKeyName'] = undefined;

/**
 * @member {String} clientId
 */
SecurityConfiguration.prototype['clientId'] = undefined;

/**
 * @member {String} clientSecret
 */
SecurityConfiguration.prototype['clientSecret'] = undefined;

/**
 * @member {String} realm
 */
SecurityConfiguration.prototype['realm'] = undefined;

/**
 * @member {String} appName
 */
SecurityConfiguration.prototype['appName'] = undefined;

/**
 * @member {String} scopeSeparator
 */
SecurityConfiguration.prototype['scopeSeparator'] = undefined;

/**
 * @member {Object.<String, Object>} additionalQueryStringParams
 */
SecurityConfiguration.prototype['additionalQueryStringParams'] = undefined;

/**
 * @member {Boolean} useBasicAuthenticationWithAccessCodeGrant
 */
SecurityConfiguration.prototype['useBasicAuthenticationWithAccessCodeGrant'] = undefined;

/**
 * @member {Boolean} enableCsrfSupport
 */
SecurityConfiguration.prototype['enableCsrfSupport'] = undefined;






export default SecurityConfiguration;

