/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SwaggerResource model module.
 * @module gp.backend.model/SwaggerResource
 * @version v0
 */
class SwaggerResource {
    /**
     * Constructs a new <code>SwaggerResource</code>.
     * @alias module:gp.backend.model/SwaggerResource
     */
    constructor() { 
        
        SwaggerResource.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SwaggerResource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:gp.backend.model/SwaggerResource} obj Optional instance to populate.
     * @return {module:gp.backend.model/SwaggerResource} The populated <code>SwaggerResource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwaggerResource();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('swaggerVersion')) {
                obj['swaggerVersion'] = ApiClient.convertToType(data['swaggerVersion'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
SwaggerResource.prototype['name'] = undefined;

/**
 * @member {String} url
 */
SwaggerResource.prototype['url'] = undefined;

/**
 * @member {String} swaggerVersion
 */
SwaggerResource.prototype['swaggerVersion'] = undefined;

/**
 * @member {String} location
 */
SwaggerResource.prototype['location'] = undefined;






export default SwaggerResource;

