/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UiConfiguration model module.
 * @module gp.backend.model/UiConfiguration
 * @version v0
 */
class UiConfiguration {
    /**
     * Constructs a new <code>UiConfiguration</code>.
     * @alias module:gp.backend.model/UiConfiguration
     */
    constructor() { 
        
        UiConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UiConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:gp.backend.model/UiConfiguration} obj Optional instance to populate.
     * @return {module:gp.backend.model/UiConfiguration} The populated <code>UiConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UiConfiguration();

            if (data.hasOwnProperty('deepLinking')) {
                obj['deepLinking'] = ApiClient.convertToType(data['deepLinking'], 'Boolean');
            }
            if (data.hasOwnProperty('displayOperationId')) {
                obj['displayOperationId'] = ApiClient.convertToType(data['displayOperationId'], 'Boolean');
            }
            if (data.hasOwnProperty('defaultModelsExpandDepth')) {
                obj['defaultModelsExpandDepth'] = ApiClient.convertToType(data['defaultModelsExpandDepth'], 'Number');
            }
            if (data.hasOwnProperty('defaultModelExpandDepth')) {
                obj['defaultModelExpandDepth'] = ApiClient.convertToType(data['defaultModelExpandDepth'], 'Number');
            }
            if (data.hasOwnProperty('defaultModelRendering')) {
                obj['defaultModelRendering'] = ApiClient.convertToType(data['defaultModelRendering'], 'String');
            }
            if (data.hasOwnProperty('displayRequestDuration')) {
                obj['displayRequestDuration'] = ApiClient.convertToType(data['displayRequestDuration'], 'Boolean');
            }
            if (data.hasOwnProperty('docExpansion')) {
                obj['docExpansion'] = ApiClient.convertToType(data['docExpansion'], 'String');
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], Object);
            }
            if (data.hasOwnProperty('maxDisplayedTags')) {
                obj['maxDisplayedTags'] = ApiClient.convertToType(data['maxDisplayedTags'], 'Number');
            }
            if (data.hasOwnProperty('operationsSorter')) {
                obj['operationsSorter'] = ApiClient.convertToType(data['operationsSorter'], 'String');
            }
            if (data.hasOwnProperty('showExtensions')) {
                obj['showExtensions'] = ApiClient.convertToType(data['showExtensions'], 'Boolean');
            }
            if (data.hasOwnProperty('showCommonExtensions')) {
                obj['showCommonExtensions'] = ApiClient.convertToType(data['showCommonExtensions'], 'Boolean');
            }
            if (data.hasOwnProperty('tagsSorter')) {
                obj['tagsSorter'] = ApiClient.convertToType(data['tagsSorter'], 'String');
            }
            if (data.hasOwnProperty('validatorUrl')) {
                obj['validatorUrl'] = ApiClient.convertToType(data['validatorUrl'], 'String');
            }
            if (data.hasOwnProperty('supportedSubmitMethods')) {
                obj['supportedSubmitMethods'] = ApiClient.convertToType(data['supportedSubmitMethods'], ['String']);
            }
            if (data.hasOwnProperty('swaggerBaseUiUrl')) {
                obj['swaggerBaseUiUrl'] = ApiClient.convertToType(data['swaggerBaseUiUrl'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} deepLinking
 */
UiConfiguration.prototype['deepLinking'] = undefined;

/**
 * @member {Boolean} displayOperationId
 */
UiConfiguration.prototype['displayOperationId'] = undefined;

/**
 * @member {Number} defaultModelsExpandDepth
 */
UiConfiguration.prototype['defaultModelsExpandDepth'] = undefined;

/**
 * @member {Number} defaultModelExpandDepth
 */
UiConfiguration.prototype['defaultModelExpandDepth'] = undefined;

/**
 * @member {module:gp.backend.model/UiConfiguration.DefaultModelRenderingEnum} defaultModelRendering
 */
UiConfiguration.prototype['defaultModelRendering'] = undefined;

/**
 * @member {Boolean} displayRequestDuration
 */
UiConfiguration.prototype['displayRequestDuration'] = undefined;

/**
 * @member {module:gp.backend.model/UiConfiguration.DocExpansionEnum} docExpansion
 */
UiConfiguration.prototype['docExpansion'] = undefined;

/**
 * @member {Object} filter
 */
UiConfiguration.prototype['filter'] = undefined;

/**
 * @member {Number} maxDisplayedTags
 */
UiConfiguration.prototype['maxDisplayedTags'] = undefined;

/**
 * @member {module:gp.backend.model/UiConfiguration.OperationsSorterEnum} operationsSorter
 */
UiConfiguration.prototype['operationsSorter'] = undefined;

/**
 * @member {Boolean} showExtensions
 */
UiConfiguration.prototype['showExtensions'] = undefined;

/**
 * @member {Boolean} showCommonExtensions
 */
UiConfiguration.prototype['showCommonExtensions'] = undefined;

/**
 * @member {module:gp.backend.model/UiConfiguration.TagsSorterEnum} tagsSorter
 */
UiConfiguration.prototype['tagsSorter'] = undefined;

/**
 * @member {String} validatorUrl
 */
UiConfiguration.prototype['validatorUrl'] = undefined;

/**
 * @member {Array.<String>} supportedSubmitMethods
 */
UiConfiguration.prototype['supportedSubmitMethods'] = undefined;

/**
 * @member {String} swaggerBaseUiUrl
 */
UiConfiguration.prototype['swaggerBaseUiUrl'] = undefined;





/**
 * Allowed values for the <code>defaultModelRendering</code> property.
 * @enum {String}
 * @readonly
 */
UiConfiguration['DefaultModelRenderingEnum'] = {

    /**
     * value: "example"
     * @const
     */
    "example": "example",

    /**
     * value: "model"
     * @const
     */
    "model": "model"
};


/**
 * Allowed values for the <code>docExpansion</code> property.
 * @enum {String}
 * @readonly
 */
UiConfiguration['DocExpansionEnum'] = {

    /**
     * value: "none"
     * @const
     */
    "none": "none",

    /**
     * value: "list"
     * @const
     */
    "list": "list",

    /**
     * value: "full"
     * @const
     */
    "full": "full"
};


/**
 * Allowed values for the <code>operationsSorter</code> property.
 * @enum {String}
 * @readonly
 */
UiConfiguration['OperationsSorterEnum'] = {

    /**
     * value: "alpha"
     * @const
     */
    "alpha": "alpha",

    /**
     * value: "method"
     * @const
     */
    "method": "method"
};


/**
 * Allowed values for the <code>tagsSorter</code> property.
 * @enum {String}
 * @readonly
 */
UiConfiguration['TagsSorterEnum'] = {

    /**
     * value: "alpha"
     * @const
     */
    "alpha": "alpha"
};



export default UiConfiguration;

