/**
 * backend-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkingDay model module.
 * @module gp.backend.model/WorkingDay
 * @version 1.0.0
 */
class WorkingDay {
    /**
     * Constructs a new <code>WorkingDay</code>.
     * @alias module:gp.backend.model/WorkingDay
     */
    constructor() { 
        
        WorkingDay.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkingDay</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:gp.backend.model/WorkingDay} obj Optional instance to populate.
     * @return {module:gp.backend.model/WorkingDay} The populated <code>WorkingDay</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkingDay();

            if (data.hasOwnProperty('day')) {
                obj['day'] = ApiClient.convertToType(data['day'], 'String');
            }
            if (data.hasOwnProperty('hour')) {
                obj['hour'] = ApiClient.convertToType(data['hour'], 'Number');
            }
            if (data.hasOwnProperty('minute')) {
                obj['minute'] = ApiClient.convertToType(data['minute'], 'Number');
            }
            if (data.hasOwnProperty('periodInMinutes')) {
                obj['periodInMinutes'] = ApiClient.convertToType(data['periodInMinutes'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:gp.backend.model/WorkingDay.DayEnum} day
 */
WorkingDay.prototype['day'] = undefined;

/**
 * @member {Number} hour
 */
WorkingDay.prototype['hour'] = undefined;

/**
 * @member {Number} minute
 */
WorkingDay.prototype['minute'] = undefined;

/**
 * @member {Number} periodInMinutes
 */
WorkingDay.prototype['periodInMinutes'] = undefined;





/**
 * Allowed values for the <code>day</code> property.
 * @enum {String}
 * @readonly
 */
WorkingDay['DayEnum'] = {

    /**
     * value: "Sunday"
     * @const
     */
    "Sunday": "Sunday",

    /**
     * value: "Monday"
     * @const
     */
    "Monday": "Monday",

    /**
     * value: "Tuesday"
     * @const
     */
    "Tuesday": "Tuesday",

    /**
     * value: "Wednesday"
     * @const
     */
    "Wednesday": "Wednesday",

    /**
     * value: "Thursday"
     * @const
     */
    "Thursday": "Thursday",

    /**
     * value: "Friday"
     * @const
     */
    "Friday": "Friday",

    /**
     * value: "Saturday"
     * @const
     */
    "Saturday": "Saturday"
};



export default WorkingDay;

